### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by chrisoberle** [gocd-contrib/email-notifier#3]
I've built and installed the plugin and restarted Go.....now what do I do?  

Please advise.

I don't see any place to configure this plugin for use in a pipeline.

**Comment by srinivasupadhya** [comment]
as mentioned [here](https://github.com/srinivasupadhya/email-notifier/blob/master/README.md) you will need to customise the plugin to suit your needs. here is the [sample data](https://github.com/gocd/gocd/issues/867) available to the plugin. Edit SMTP settings [here](https://github.com/srinivasupadhya/email-notifier/blob/master/src/com/tw/go/plugin/EmailNotificationPluginImpl.java#L70). Write email sending logic (which email-id to send for which stage for what state (scheduled/re-scheduled/passed/failed/cancelled) etc.

**Comment by chrisoberle** [comment]
Hey there.   Thanks for the prompt reply.  I've seen the info at the links you provided (thanks!).  I guess my question is, I had expected to see the plugin exposed in go's webui somehow.  I see where I can configure the smtp server settings and i'm able to send a test email.   I dont see where I can the notification unit of work to the configuration within a stage.

What I'm trying to do is send email when a stage reaches a certain state and have the email contain information on say, which server was deployed to, etc...   

Am I missing maybe a different plugin that turns on the notification functionality within the web ui?

Thanks!

**Comment by srinivasupadhya** [comment]
> i'm able to send a test email
great!

> I dont see where I can configure the notification unit of work within a stage. What I'm trying to do is send email when a stage reaches a certain state and have the email contain information on say, which server was deployed to, etc...
the configuration bit is not implemented. it going to be varied based on requirements, eg:
* someone wanted to send an email to a particular account everytime a stage failed
* someone wanted to send it only to "breakers" (computed from `build-cause`)
* while someone wanted to send emails based on `pipeline-group` (group to account mapping was stored in a flat file like `~/.email-configuration` that was read & understood by plugin)

it was really difficult to comeup with a generic implementation & hence i haven't implemented that part.

**Comment by michaeloa** [comment]
Hmm. I'm sure that there are many possible use-cases, but I do feel that there are a few core use-cases that would cover the vast majority of user needs - i.e., send to breaker(s) and send to mailing list.

Honestly, I find the lack of this functionality in the GoCD core puzzling. Chat, IRC etc are fine also, but asynchronous communication is pretty much a core element in this kind of system,

**Comment by srinivasupadhya** [comment]
> Hmm. I'm sure that there are many possible use-cases, but I do feel that there are a few core use-cases that would cover the vast majority of user needs - i.e., send to breaker(s) and send to mailing list.

With Go v15.2 plugins can take [settings](http://www.go.cd/2015/06/18/plugin-settings.html) from admins. I have updated the plugin to do so, that way you will not need to change code to configure plugin. Extending this to take configuration about what email to send to whom for what pipelines should be easy enough i suppose.

**Comment by michaeloa** [comment]
Heh - we just last week updated to v15.1, specifically so we could try this plugin. Need to push another update then. :-D

I think it would be useful to have this specced in the settings. It's probably not a huge problem to fork the repo and add changes in the code for most developers, but it does increase the threshold for usage which seems unnecessary.

**Comment by srinivasupadhya** [comment]
the 15.2 GA isn't out yet, so you will need to wait a bit :)

and i agree with the threshold bit, need to make it configurable to cater as many as possible. will give it a shot when i find time.

**Comment by dsenecalb** [comment]
Hi, reading the code. The plugin requires information of the SMTP server (server, username, password). However, the server where the go is installed into has ability to send email without using the SMTP settings and just from the local server. 

Thanks.

**Comment by srinivasupadhya** [comment]
then you do not need configuration at all i assume. you can just get rid of the code [here](https://github.com/gocd-contrib/email-notifier/blob/master/src/com/tw/go/plugin/EmailNotificationPluginImpl.java#L103) & customize it for your use case.

**Comment by iboppana** [comment]
Hi,

Before we installed this plugin we used to configure for each user under profile what pipelines/stages and states they would like to be notified.
After installing this plugin i am under the impression that at stage level (some where while creation a stage) there will be a option for notification.

I dont see any. 
How is this different than what comes with the normal go installation.
Whats the value add i am getting installing this plugin.

Appreciate your input in this regard.

Thanks
  Indrani

**Comment by srinivasupadhya** [comment]
this plugin will get a call back everytime a stage is scheduled or completed (passed/failed/cancelled). it will have some data payload like pipelin-group name, pipeline name, stage name, materials & commits for that material etc. you can write custom logic for sending email, i.e. who to send email on what conditions etc. which you cannot currently do in Go.

**Comment by iboppana** [comment]
Srinivas,
First and foremost thanks for the prompt reply.
Can u please point me to documentation or example which details how to configure this plugin or a callback  to send email on stage failure of a particular pipeline.

Rightnow i see the plugin installed in Admin plugins, and configured with right smtp info.

Also does this plugin work well with GO version 14.3

Thanks
  Indrani

**Comment by srinivasupadhya** [comment]
notification plugins work >= 15.1. You can refer to [dev docs](http://www.go.cd/documentation/developer/writing_go_plugins/notification/json_message_based_notification_extension.html) and [code](https://github.com/gocd-contrib/email-notifier/blob/master/src/com/tw/go/plugin/EmailNotificationPluginImpl.java#L98) to figure out how you can customize it.
